problem3/scrape_and_display/config/routes.rb
ScrapeAndDisplay::Application.routes.draw do
  get '/' => 'home#index', :as => 'home'

end

problem3/scrape_and_display/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

problem3/scrape_and_display/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    page_no          = params[:page_no] || 0
    records          = JSON.parse(File.read(Rails.root.to_s + '/universities_rankings.json'))
    @universities    = records.slice(page_no.to_i * 10, 10)
    @number_of_pages = records.length/10
  end
end

problem3/scrape_and_display/app/helpers/application_helper.rb
module ApplicationHelper
end

problem3/scrape_and_display/app/helpers/home_helper.rb
module HomeHelper
end

problem3/scrape_and_display/app/views/home/index.html.erb
<table>
    <tr>
      <td>Name</td>
      <td>Rank</td>
      <td>Tution Fee</td>
      <td>Enrollmonts</td>
      </tr>
  <% @universities.each do |university| %>
    <tr>
      <td><%= university['name'] %></td>
      <td><%= university['rank'] %></td>
      <td><%= university['tution_fee'] %></td>
      <td><%= university['enrollemnts'] %></td>
      </tr>
  <% end %>
</table>
<% for page in 0..@number_of_pages do %>
  <%= link_to page + 1,  home_url(:page_no => page)%>
<% end %>

problem3/scrape_and_display/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScrapeAndDisplay</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>